travis: replace the script
The previous was a broken copy-pasta mismash from hvr's example and tmcdonell's cuda bindings package

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,72 +1,110 @@
-# RRN: Copied from template here: https://github.com/hvr/multi-ghc-travis/blob/master/README.md#ghc-head-snapshots
-
-# NB: don't set `language: haskell` here
-
-# The following enables several GHC versions to be tested; often it's enough to test only against the last release in a major GHC version. Feel free to omit lines listings versions you don't need/want testing for.
+language: haskell
 env:
- - CABALVER=1.18 GHCVER=7.8.2
- - CABALVER=1.18 GHCVER=7.8.3
- - CABALVER=1.18 GHCVER=7.8.4
- - CABALVER=1.22 GHCVER=7.10.1
- - CABALVER=head GHCVER=head
+  global:
+    - HAPPY=1.19.5
+    - ALEX=3.1.4
+
+  matrix:
+    - CUDA=6.5-14 GHC=7.6.3
+    - CUDA=6.5-14 GHC=7.8.4
+    - CUDA=6.5-14 GHC=7.10.1
+    - CUDA=7.0-28 GHC=7.6.3
+    - CUDA=7.0-28 GHC=7.8.4
+    - CUDA=7.0-28 GHC=7.10.1
+    - CUDA=7.0-28 GHC=head
+#    - CUDA=6.0-37
 
 matrix:
-  allow_failures:
-    - env: CABALVER=head GHCVER=head
+    allow_failures:
+        - env: CUDA=7.0-28 GHC=head
 
 # Handle git submodules yourself
 git:
     submodules: false
 
-# Note: the distinction between `before_install` and `install` is not important.
 before_install:
- # Use sed to replace the SSH URL with the public URL, then initialize submodules
- - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
- - git submodule update --init
+    # Use sed to replace the SSH URL with the public URL, then initialize submodules
+    - travis_echo "Setting up submodules"
+    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
+    - git submodule update --init
 
- - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
- - travis_retry sudo apt-get update
- - travis_retry sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER # see note about happy/alex
- - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH
- - travis_retry sudo apt-get install -y c2hs
- - travis_retry sudo apt-get install happy-1.19.5 alex-3.1.4
+    # If travis doesn't have the version of GHC that we want, get it from hvr's PPA
+    - echo "Setting up GHC"
+    - travis_retry sudo add-apt-repository -y ppa:hvr/ghc
+    - travis_retry sudo apt-get update -qq
+    # The CUDA bindings require a newer version of c2hs than available from apt
+    # - travis_retry sudo apt-get install -y c2hs
+    - export PATH=/usr/local/ghc/${GHC}/bin:${PATH}
+    - |
+        if [ $(ghc --numeric-version) != ${GHC} ]; then
+            travis_retry sudo apt-get install -y ghc-${GHC}
+            export PATH=/opt/ghc/${GHC}/bin:${PATH}
+        fi
+    # - |
+    #     if [ ${GHC} = "head" ]; then
+    #         travis_retry sudo apt-get install -y cabal-install-head
+    #         export PATH=/opt/cabal/head/bin:${PATH}
+    #     fi
 
- - echo "Installing CUDA library"
- - travis_retry wget http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1204/x86_64/cuda-repo-ubuntu1204_${CUDA}_amd64.deb
- - travis_retry sudo dpkg -i cuda-repo-ubuntu1204_${CUDA}_amd64.deb
- - travis_retry sudo apt-get update -qq
- - export CUDA_APT=${CUDA%-*}
- - export CUDA_APT=${CUDA_APT/./-}
- - travis_retry sudo apt-get install -y cuda-drivers cuda-core-${CUDA_APT} cuda-cudart-dev-${CUDA_APT}
- - travis_retry sudo apt-get clean
- - export CUDA_HOME=/usr/local/cuda-${CUDA%%-*}
- - export LD_LIBRARY_PATH=${CUDA_HOME}/lib64:${LD_LIBRARY_PATH}
- - export PATH=${CUDA_HOME}/bin:${PATH}
+    # If we want to build c2hs from source, ghc-7.8 and later will require newer
+    # versions of happy and alex
+    - |
+        if [ ${GHC%.*} != 7.6 ]; then
+            export HAPPY=1.19.5
+            export ALEX=3.1.4
+            travis_retry sudo apt-get install -y alex-${ALEX} happy-${HAPPY}
+            export PATH=/opt/alex/${ALEX}/bin:/opt/happy/${HAPPY}/bin:${PATH}
+        fi
+    - cabal install c2hs
 
+    - echo "Installing CUDA library"
+    - travis_retry wget http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1204/x86_64/cuda-repo-ubuntu1204_${CUDA}_amd64.deb
+    - travis_retry sudo dpkg -i cuda-repo-ubuntu1204_${CUDA}_amd64.deb
+    - travis_retry sudo apt-get update -qq
+    - export CUDA_APT=${CUDA%-*}
+    - export CUDA_APT=${CUDA_APT/./-}
+    - travis_retry sudo apt-get install -y cuda-drivers cuda-core-${CUDA_APT} cuda-cudart-dev-${CUDA_APT}
+    - travis_retry sudo apt-get clean
+    - export CUDA_HOME=/usr/local/cuda-${CUDA%%-*}
+    - export LD_LIBRARY_PATH=${CUDA_HOME}/lib64:${LD_LIBRARY_PATH}
+    - export PATH=${CUDA_HOME}/bin:${PATH}
 
 install:
- - cabal --version
- - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
- - travis_retry cabal update
- - export PKGS=" ./Obsidian/ ./src/ ./Applications/Mandel ./Applications/Histogram "
- - cabal install --only-dependencies --enable-tests --enable-benchmarks $PKGS
+    - cabal --version
+    - c2hs --version
+    - nvcc --version
+    - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
+    - export PKGS="./Obsidian/ ./src/ ./Applications/Mandel ./Applications/Histogram"
+    - cabal install --only-dependencies --enable-tests --enable-benchmarks ${PKGS}
 
-# Here starts the actual work to be performed for the package under test; any command which exits with a non-zero exit code causes the build to fail.
+# Here starts the actual work to be performed for the package under test; any
+# command which exits with a non-zero exit code causes the build to fail.
 script:
- - for path in $PKGS; do
-    cd ./$path;
-    cabal configure --enable-tests --enable-benchmarks -v2;
-    cabal build;
-    cabal test;
-    cabal bench;
-    cabal sdist;
-    cd -;
-   done;
+    - |
+        for PKG in ${PKGS}; do
+            # Check the build
+            pushd ${PKG}
+            cabal configure --enable-tests --enable-benchmarks -v2 -flib-Werror
+            cabal build
+            cabal haddock
+            cabal test --show-details=always
+            cabal bench
 
-# There's no Setup.hs... Perhaps there should be?
-# Feel free to add this before "cabal sdist" above:
-#   cabal check;
+            # Check the source distribution can be generated, built, and installed
+            cabal sdist
+            export SRC_TGZ=$(cabal info . | awk '{print $2 ".tar.gz";exit}')
+            cd dist
+            if [ -f "$SRC_TGZ" ]; then
+                cabal install --force-reinstalls ${SRC_TGZ}
+            else
+                echo "'$SRC_TGZ': not found"
+                exit 1
+            fi
+
+            popd
+        done
 
 after_failure:
     - dmesg
     - ls -R /usr/local/cuda*
+
